orbs:
  slack: circleci/slack@3.4.2

version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:20.4.0-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install

      - checkout

      - restore_cache:
          name: Restore Npm Package Cache
          key: npm-dependencies-{{ checksum "package-lock.json" }}

      - run: npm install -g node-gyp
      - run: npm install
      - run: apt install -y google-chrome-stable

      - save_cache:
          name: Save Npm Package Cache
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          paths:
             - node_modules

      - run:
          name: Run tests
          command: npm run wdio