orbs:
  slack: circleci/slack@3.4.2

version: 2.1
jobs:
  build:
    docker:
      
    - image: node:22.14.0
    - image: selenium/node-chrome:latest
    working_directory: ~/repo

    steps:

      - checkout

      - restore_cache:
          name: Restore Npm Package Cache
          key: npm-dependencies-{{ checksum "package-lock.json" }}

      - run: npm install -g node-gyp
      - run: npm install

      - save_cache:
          name: Save Npm Package Cache
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          paths:
             - node_modules

      - run:
          name: Run tests
          command: npm run test:features