version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
      - image: selenium/standalone-chrome:129.0.6668.100-20250222

    working_directory: ~/repo

    steps:

      - checkout
      - restore_cache:
          name: Restore Npm Package Cache
          key: npm-dependencies-{{ checksum "package-lock.json" }}

      - run: npm install -g node-gyp
      - run: npm install

      - save_cache:
          name: Save Npm Package Cache
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          paths:
             - node_modules

      - run:
          name: Run tests
          command: npm run wdio

      # - run:
      #     name: Generate report
      #     command: npm run report
      #     when: always

      # - store_artifacts:
      #     path: allure-report

workflows:
  version: 2
  commit:
     jobs:
       - build

  nightly:
    triggers:
      - schedule:
          cron: "* 5 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build