orbs:
  slack: circleci/slack@3.4.2

version: 2.1
jobs:
  build:
    docker:
      - image: pdovwork/seavus_code_talks:latest
      - image: selenium/standalone-chrome:latest
    working_directory: ~/repo

    steps:

      - checkout
      - restore_cache:
          name: Restore Npm Package Cache
          key: npm-dependencies-{{ checksum "package-lock.json" }}

      - run: npm install -g node-gyp
      - run: npm install

      - save_cache:
          name: Save Npm Package Cache
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          paths:
             - node_modules

      - run:
          name: Run tests
          command: npm run web -- --reporters=allure --maxInstances=1

      - run:
          name: Generate report
          command: npm run report:generate
          when: always

      - store_artifacts:
          path: allure-report

workflows:
  version: 2
  commit:
     jobs:
       - build

  nightly:
    triggers:
      - schedule:
          cron: "* 5 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build