version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/node:20.4.0-browsers
    steps:

      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install

      - restore_cache:
          name: Restore Npm Package Cache
          key: npm-dependencies-{{ checksum "package-lock.json" }}

      - run: npm install -g node-gyp
      - run: npm install


      - save_cache:
          name: Save Npm Package Cache
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          paths:
             - node_modules

      - run:
          name: Run tests
          command: npm run test:features